### PR TITLE
Upgrade to Terria 7.1.0

### PR DESCRIPTION
**Pull request by na9da**

### CODE REVIEW

**Comment by meh9** [comment]
Looks ok to me!

**Comment by juan-guerschman** [comment]
what happens now? When is this made effective?

**Comment by AnaBelgun** [comment]
@juan-guerschman Nanda will make it available in production soon

**Comment by AnaBelgun** [comment]
@juan-guerschman @na9da has updated the app: https://map.geo-rapp.org/ it has the latest terria version now

**Pull request merged**
